import type { QuestionOption } from '../types/coach';

// Mirrors iOS CoachQuestions.swift — the automated Q&A wizard the coach
// runs when it detects a venue search. The questions are hard-coded for
// now; later they can be generated by the AI.

export interface QuestionDef {
  text: string;
  options: QuestionOption[];
}

// ─── Shared location chips (Q2 for every category) ────────────────────────────

// `value` strings are internal keys consumed by `coachLocationFilter()` —
// they are NOT shown to the user (that's `label`) and are no longer fed to
// the AI (venue searches run entirely through this local wizard).
export const LocationValue = {
  drive:   'drive15',   // GPS distance — "within a 15-minute drive"
  capital: 'capital',   // greater Reykjavík + Reykjanes peninsula
  south:   'south',
  north:   'north',
  east:    'east',
  west:    'west',
} as const;

export const LOCATION_OPTIONS: QuestionOption[] = [
  { label: '🚗 15-min drive',     value: LocationValue.drive },
  { label: 'Reykjavík / Capital', value: LocationValue.capital },
  { label: 'South Iceland',       value: LocationValue.south },
  { label: 'North Iceland',       value: LocationValue.north },
  { label: 'East Iceland',        value: LocationValue.east },
  { label: 'West Iceland',        value: LocationValue.west },
];

const LOCATION_Q: QuestionDef = {
  text: 'Where in Iceland?',
  options: LOCATION_OPTIONS,
};

// ─── Location filtering (coordinate-based) ────────────────────────────────────
//
// The wizard's "Where in Iceland?" answer becomes a CoachLocationFilter,
// which CoachScreen applies to the venues it gets back from the API.
// Regions are derived from each venue's lat/long — the `city` field is too
// inconsistent to bucket on (postal-code prefixes, spelling variants) — so
// any new venue is classified automatically with no manual region list to
// maintain. Mirrors iOS icelandRegion().

export type IcelandRegion = 'capital' | 'south' | 'north' | 'east' | 'west';

/**
 * Buckets a coordinate into one of the chip regions. Greater Reykjavík +
 * the Reykjanes peninsula are 'capital'; the rest of the country splits
 * roughly by cardinal direction. Boundaries are intentionally coarse —
 * they only need to separate Akureyri (N), the eastfjords (E),
 * Borgarnes/Akranes/Snæfellsnes (W) and the south coast (S) from the
 * capital area.
 */
export function icelandRegion(lat: number, lon: number): IcelandRegion {
  // Greater Reykjavík + Reykjanes (Keflavík/Njarðvík) — the southwest corner.
  if (lat >= 63.78 && lat <= 64.25 && lon >= -22.8 && lon <= -21.55) {
    return 'capital';
  }
  if (lon >= -16.5) return 'east';                  // eastfjords: Egilsstaðir, Höfn
  if (lat >= 65.0 && lon >= -19.5) return 'north';  // Akureyri & the north coast
  // West must be NORTH of the capital box (lat ≥ 64.25). Without the
  // latitude gate, south-coast venues just east of greater Reykjavík
  // (e.g. Selfoss/Hella at ~63.9N) would be bucketed West and dropped
  // from the "South Iceland" chip.
  if (lat >= 64.25 && lon <= -21.0) return 'west';  // Borgarnes, Akranes, Westfjords
  return 'south';                                    // Selfoss, Hella, Vík, Vestmannaeyjar
}

export type CoachLocationFilter =
  | { kind: 'nearbyDrive' }          // "15-min drive" → GPS distance from the user
  | { kind: 'region'; region: IcelandRegion }
  | { kind: 'none' };

/**
 * Pulls the location filter out of the wizard answers. The location chip
 * can sit at a different step per category, so we scan for a known value
 * rather than assuming a position. Returns 'none' if the member never
 * picked one.
 */
export function coachLocationFilter(answers: string[]): CoachLocationFilter {
  for (const answer of answers) {
    switch (answer) {
      case LocationValue.drive:   return { kind: 'nearbyDrive' };
      case LocationValue.capital: return { kind: 'region', region: 'capital' };
      case LocationValue.south:   return { kind: 'region', region: 'south' };
      case LocationValue.north:   return { kind: 'region', region: 'north' };
      case LocationValue.east:    return { kind: 'region', region: 'east' };
      case LocationValue.west:    return { kind: 'region', region: 'west' };
      default:                    continue;
    }
  }
  return { kind: 'none' };
}

// ─── Training-type → narrower category override ───────────────────────────────
//
// Some "what type?" chips map to a more specific DB category than the
// broad one. When the member picked such a type we query that category so
// the right venue surfaces instead of the whole list — e.g. "MMA & Combat"
// → "MMA", which is how Mjölnir (the only MMA-tagged venue) is found. Only
// types that exist as real venue tags are mapped (verified against the
// catalogue); weightlifting/spinning/CrossFit have no distinct tag, so
// they fall through to the broad category. Returns null when no override
// applies. Keep the cases in sync with the `value`s in VENUE_QUESTIONS.
export function coachCategoryOverride(answers: string[]): string | null {
  for (const answer of answers) {
    switch (answer) {
      case 'MMA and combat sports':
        return 'MMA';
      // Both the gym set's "Pilates" chip and the yoga set's "Pilates
      // reformer" chip target the Pilates category — reformer is a
      // Pilates apparatus, so a member picking it wants Pilates studios.
      case 'pilates':
      case 'pilates reformer':
        return 'Pilates';
      default:
        continue;
    }
  }
  return null;
}

// ─── Question sets per category ───────────────────────────────────────────────

export const VENUE_QUESTIONS: Record<string, QuestionDef[]> = {
  gym: [
    {
      text: 'What type of training are you after?',
      options: [
        { label: 'Weightlifting', value: 'weightlifting' },
        { label: 'MMA & Combat',  value: 'MMA and combat sports' },
        { label: 'Spinning',      value: 'spinning classes' },
        { label: 'CrossFit',      value: 'CrossFit' },
        { label: 'Pilates',       value: 'pilates' },
        { label: 'Other',         value: '', isOther: true },
      ],
    },
    LOCATION_Q,
    {
      text: 'Any must-have amenities?',
      options: [
        { label: 'Has sauna',     value: 'with a sauna' },
        { label: 'Open evenings', value: 'open in the evening' },
        { label: 'No preference', value: '' },
      ],
    },
  ],

  lagoon: [
    {
      text: 'What kind of experience?',
      options: [
        { label: 'Geothermal pools',    value: 'geothermal pools' },
        { label: 'Sauna & cold plunge', value: 'sauna and cold plunge' },
        { label: 'Luxury spa',          value: 'luxury spa experience' },
      ],
    },
    LOCATION_Q,
  ],

  yoga: [
    {
      text: 'What style of class?',
      options: [
        { label: 'Vinyasa & Flow',    value: 'vinyasa flow yoga' },
        { label: 'Yin & Restorative', value: 'yin and restorative yoga' },
        { label: 'Pilates reformer',  value: 'pilates reformer' },
        { label: 'Hot yoga',          value: 'hot yoga' },
        { label: 'Other',             value: '', isOther: true },
      ],
    },
    LOCATION_Q,
    {
      text: 'Your experience level?',
      options: [
        { label: 'Beginner',     value: 'suitable for beginners' },
        { label: 'Intermediate', value: 'intermediate level' },
        { label: 'Advanced',     value: 'advanced level' },
        { label: 'Any level',    value: '' },
      ],
    },
  ],

  swimming: [
    {
      text: 'What are you after?',
      options: [
        { label: 'Lap swimming',     value: 'lap swimming lanes' },
        { label: 'Hot tubs & relax', value: 'hot tubs and relaxation' },
        { label: 'Outdoor pool',     value: 'outdoor heated pool' },
        { label: 'Family-friendly',  value: 'family-friendly facilities' },
      ],
    },
    LOCATION_Q,
    {
      text: 'Any extras?',
      options: [
        { label: 'Has steam room', value: 'with a steam room' },
        { label: 'Has sauna',      value: 'with a sauna' },
        { label: 'Open early',     value: 'open early in the morning' },
        { label: 'No preference',  value: '' },
      ],
    },
  ],

  spa: [
    {
      text: 'What type of experience?',
      options: [
        { label: 'Traditional sauna',  value: 'traditional sauna' },
        { label: 'Steam room',         value: 'steam room' },
        { label: 'Full spa treatment', value: 'full spa treatment' },
        { label: 'Sauna & pool combo', value: 'sauna and pool combination' },
        { label: 'Other',              value: '', isOther: true },
      ],
    },
    LOCATION_Q,
  ],

  // LifePass has a single golf venue today (Golf Club Vestmannaeyja, in the
  // South). Golf has no sub-types worth filtering on, so we ask only the
  // shared location question — no decorative chips that don't actually
  // narrow anything. As more courses are added, location filtering kicks in.
  golf: [LOCATION_Q],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns a category key if the message is a venue search, else null. Order matters. */
export function detectVenueCategory(text: string): string | null {
  const t = text.toLowerCase();
  if (/\bgym\b|gyms|workout|fitness|weightlift|crossfit|\bmma\b|combat|spinning/.test(t)) return 'gym';
  // Checked before "lagoon" so a prompt mentioning both (e.g. the "Spa &
  // Lagoons" category card, "...spa or lagoon evening...") resolves to the
  // spa wizard, matching that card's own category id — a query that's
  // genuinely lagoon-only never contains a spa keyword, so this ordering
  // doesn't change matching for lagoon-only prompts.
  if (/\bspa\b|saunas?|steam room|wellness|recovery/.test(t)) return 'spa';
  if (/lagoon|hot spring|geothermal|thermal pool/.test(t)) return 'lagoon';
  if (/\byoga\b|pilates|vinyasa|yin yoga|hot yoga/.test(t)) return 'yoga';
  if (/\bpool\b|pools|swimming|swim lane/.test(t)) return 'swimming';
  if (/\bgolf\b|golfing|driving range/.test(t)) return 'golf';
  return null;
}
